Repository CAP1Sup/Intellistep, pull requests merged in 2021-08, with the labels that each got.

#84 Fix M18/M84 use
  src/hardware/encoder.cpp
  src/hardware/timers.cpp
  src/main/main.cpp
  src/software/parser.cpp
Labels: bug

#83 Step-dir under ideal conditions
  src/config/config.h
  src/config/config_adv.h
  src/hardware/flash.cpp
  src/hardware/motor.cpp
  src/hardware/motor.h
  src/software/fastSine.cpp
  src/software/sanityCheck.h
Labels: bug

#97 motor.step() uses a direct value stepChange instead of a flag useMultiplier
  src/hardware/motor.cpp
  src/hardware/motor.h
  src/hardware/timers.cpp
  src/software/macros.h
Labels: improvement

#98 Zero the encoder after the motor is enabled
  src/main/main.cpp
Labels: improvement

#96 Rev ing schematics
  .gitignore
  Kicad/BTTS42Bv2/BTTS42Bv2.kicad_pcb
  Kicad/BTTS42Bv2/BTTS42Bv2.pro
  Kicad/BTTS57Bv2/BNOR11.dcm
  Kicad/BTTS57Bv2/BNOR11.lib
  Kicad/BTTS57Bv2/BTTS57Bv2-cache.lib
  Kicad/BTTS57Bv2/BTTS57Bv2-rescue.dcm
  Kicad/BTTS57Bv2/BTTS57Bv2-rescue.lib
  Kicad/BTTS57Bv2/BTTS57Bv2.kicad_pcb
  Kicad/BTTS57Bv2/BTTS57Bv2.pro
  Kicad/BTTS57Bv2/BTTS57Bv2.sch
  Kicad/BTTS57Bv2/BTT_S57B_v2.0_reverseIng.0.1.1.pdf
  Kicad/BTTS57Bv2/TLE5012B.dcm
  Kicad/BTTS57Bv2/TLE5012B.lib
  Kicad/BTTS57Bv2/el-0631.dcm
  Kicad/BTTS57Bv2/el-0631.lib
  Kicad/BTTS57Bv2/sym-lib-table
  datasheets/Everlight-Elec-EL357N-B-TA-G_C6649.pdf
Labels: documentation

#103 Set priority grouping explicitly to 3.1(PRIO.SUBPRIO)
  platformio.ini
  src/hardware/motor.cpp
  src/main/main.cpp
Labels: bug, improvement
